/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortalPortalRouteImport } from './routes/portal/_portal'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthenticatedSearchRouteImport } from './routes/_authenticated.search'
import { Route as AuthenticatedPatientsRouteImport } from './routes/_authenticated.patients'
import { Route as AuthenticatedOcrRouteImport } from './routes/_authenticated.ocr'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated.notifications'
import { Route as AuthenticatedEmrRouteImport } from './routes/_authenticated.emr'
import { Route as AuthenticatedDoctorsRouteImport } from './routes/_authenticated.doctors'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedChatbotRouteImport } from './routes/_authenticated.chatbot'
import { Route as AuthenticatedBillingRouteImport } from './routes/_authenticated.billing'
import { Route as AuthenticatedAuditLogsRouteImport } from './routes/_authenticated.audit-logs'
import { Route as AuthenticatedAppointmentsRouteImport } from './routes/_authenticated.appointments'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated.analytics'
import { Route as PortalPortalRecordsRouteImport } from './routes/portal/_portal.records'
import { Route as PortalPortalOverviewRouteImport } from './routes/portal/_portal.overview'
import { Route as PortalPortalNotificationsRouteImport } from './routes/portal/_portal.notifications'
import { Route as PortalPortalCreateProfileRouteImport } from './routes/portal/_portal.create-profile'
import { Route as PortalPortalChatbotRouteImport } from './routes/portal/_portal.chatbot'
import { Route as PortalPortalBillsRouteImport } from './routes/portal/_portal.bills'
import { Route as PortalPortalAppointmentsRouteImport } from './routes/portal/_portal.appointments'
import { Route as AuthenticatedAiSummaryRouteImport } from './routes/_authenticated.ai.summary'
import { Route as AuthenticatedAiNotesRouteImport } from './routes/_authenticated.ai.notes'
import { Route as AuthenticatedAiClinicalSearchRouteImport } from './routes/_authenticated.ai.clinical-search'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalPortalRoute = PortalPortalRouteImport.update({
  id: '/portal/_portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSearchRoute = AuthenticatedSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPatientsRoute = AuthenticatedPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOcrRoute = AuthenticatedOcrRouteImport.update({
  id: '/ocr',
  path: '/ocr',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEmrRoute = AuthenticatedEmrRouteImport.update({
  id: '/emr',
  path: '/emr',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDoctorsRoute = AuthenticatedDoctorsRouteImport.update({
  id: '/doctors',
  path: '/doctors',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedChatbotRoute = AuthenticatedChatbotRouteImport.update({
  id: '/chatbot',
  path: '/chatbot',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBillingRoute = AuthenticatedBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAuditLogsRoute = AuthenticatedAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppointmentsRoute =
  AuthenticatedAppointmentsRouteImport.update({
    id: '/appointments',
    path: '/appointments',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const PortalPortalRecordsRoute = PortalPortalRecordsRouteImport.update({
  id: '/records',
  path: '/records',
  getParentRoute: () => PortalPortalRoute,
} as any)
const PortalPortalOverviewRoute = PortalPortalOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => PortalPortalRoute,
} as any)
const PortalPortalNotificationsRoute =
  PortalPortalNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => PortalPortalRoute,
  } as any)
const PortalPortalCreateProfileRoute =
  PortalPortalCreateProfileRouteImport.update({
    id: '/create-profile',
    path: '/create-profile',
    getParentRoute: () => PortalPortalRoute,
  } as any)
const PortalPortalChatbotRoute = PortalPortalChatbotRouteImport.update({
  id: '/chatbot',
  path: '/chatbot',
  getParentRoute: () => PortalPortalRoute,
} as any)
const PortalPortalBillsRoute = PortalPortalBillsRouteImport.update({
  id: '/bills',
  path: '/bills',
  getParentRoute: () => PortalPortalRoute,
} as any)
const PortalPortalAppointmentsRoute =
  PortalPortalAppointmentsRouteImport.update({
    id: '/appointments',
    path: '/appointments',
    getParentRoute: () => PortalPortalRoute,
  } as any)
const AuthenticatedAiSummaryRoute = AuthenticatedAiSummaryRouteImport.update({
  id: '/ai/summary',
  path: '/ai/summary',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAiNotesRoute = AuthenticatedAiNotesRouteImport.update({
  id: '/ai/notes',
  path: '/ai/notes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAiClinicalSearchRoute =
  AuthenticatedAiClinicalSearchRouteImport.update({
    id: '/ai/clinical-search',
    path: '/ai/clinical-search',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/appointments': typeof AuthenticatedAppointmentsRoute
  '/audit-logs': typeof AuthenticatedAuditLogsRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/chatbot': typeof AuthenticatedChatbotRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/doctors': typeof AuthenticatedDoctorsRoute
  '/emr': typeof AuthenticatedEmrRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/ocr': typeof AuthenticatedOcrRoute
  '/patients': typeof AuthenticatedPatientsRoute
  '/search': typeof AuthenticatedSearchRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/portal': typeof PortalPortalRouteWithChildren
  '/ai/clinical-search': typeof AuthenticatedAiClinicalSearchRoute
  '/ai/notes': typeof AuthenticatedAiNotesRoute
  '/ai/summary': typeof AuthenticatedAiSummaryRoute
  '/portal/appointments': typeof PortalPortalAppointmentsRoute
  '/portal/bills': typeof PortalPortalBillsRoute
  '/portal/chatbot': typeof PortalPortalChatbotRoute
  '/portal/create-profile': typeof PortalPortalCreateProfileRoute
  '/portal/notifications': typeof PortalPortalNotificationsRoute
  '/portal/overview': typeof PortalPortalOverviewRoute
  '/portal/records': typeof PortalPortalRecordsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/appointments': typeof AuthenticatedAppointmentsRoute
  '/audit-logs': typeof AuthenticatedAuditLogsRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/chatbot': typeof AuthenticatedChatbotRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/doctors': typeof AuthenticatedDoctorsRoute
  '/emr': typeof AuthenticatedEmrRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/ocr': typeof AuthenticatedOcrRoute
  '/patients': typeof AuthenticatedPatientsRoute
  '/search': typeof AuthenticatedSearchRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/portal': typeof PortalPortalRouteWithChildren
  '/ai/clinical-search': typeof AuthenticatedAiClinicalSearchRoute
  '/ai/notes': typeof AuthenticatedAiNotesRoute
  '/ai/summary': typeof AuthenticatedAiSummaryRoute
  '/portal/appointments': typeof PortalPortalAppointmentsRoute
  '/portal/bills': typeof PortalPortalBillsRoute
  '/portal/chatbot': typeof PortalPortalChatbotRoute
  '/portal/create-profile': typeof PortalPortalCreateProfileRoute
  '/portal/notifications': typeof PortalPortalNotificationsRoute
  '/portal/overview': typeof PortalPortalOverviewRoute
  '/portal/records': typeof PortalPortalRecordsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/appointments': typeof AuthenticatedAppointmentsRoute
  '/_authenticated/audit-logs': typeof AuthenticatedAuditLogsRoute
  '/_authenticated/billing': typeof AuthenticatedBillingRoute
  '/_authenticated/chatbot': typeof AuthenticatedChatbotRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/doctors': typeof AuthenticatedDoctorsRoute
  '/_authenticated/emr': typeof AuthenticatedEmrRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/ocr': typeof AuthenticatedOcrRoute
  '/_authenticated/patients': typeof AuthenticatedPatientsRoute
  '/_authenticated/search': typeof AuthenticatedSearchRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/portal/_portal': typeof PortalPortalRouteWithChildren
  '/_authenticated/ai/clinical-search': typeof AuthenticatedAiClinicalSearchRoute
  '/_authenticated/ai/notes': typeof AuthenticatedAiNotesRoute
  '/_authenticated/ai/summary': typeof AuthenticatedAiSummaryRoute
  '/portal/_portal/appointments': typeof PortalPortalAppointmentsRoute
  '/portal/_portal/bills': typeof PortalPortalBillsRoute
  '/portal/_portal/chatbot': typeof PortalPortalChatbotRoute
  '/portal/_portal/create-profile': typeof PortalPortalCreateProfileRoute
  '/portal/_portal/notifications': typeof PortalPortalNotificationsRoute
  '/portal/_portal/overview': typeof PortalPortalOverviewRoute
  '/portal/_portal/records': typeof PortalPortalRecordsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/analytics'
    | '/appointments'
    | '/audit-logs'
    | '/billing'
    | '/chatbot'
    | '/dashboard'
    | '/doctors'
    | '/emr'
    | '/notifications'
    | '/ocr'
    | '/patients'
    | '/search'
    | '/auth/callback'
    | '/portal'
    | '/ai/clinical-search'
    | '/ai/notes'
    | '/ai/summary'
    | '/portal/appointments'
    | '/portal/bills'
    | '/portal/chatbot'
    | '/portal/create-profile'
    | '/portal/notifications'
    | '/portal/overview'
    | '/portal/records'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/analytics'
    | '/appointments'
    | '/audit-logs'
    | '/billing'
    | '/chatbot'
    | '/dashboard'
    | '/doctors'
    | '/emr'
    | '/notifications'
    | '/ocr'
    | '/patients'
    | '/search'
    | '/auth/callback'
    | '/portal'
    | '/ai/clinical-search'
    | '/ai/notes'
    | '/ai/summary'
    | '/portal/appointments'
    | '/portal/bills'
    | '/portal/chatbot'
    | '/portal/create-profile'
    | '/portal/notifications'
    | '/portal/overview'
    | '/portal/records'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/register'
    | '/_authenticated/analytics'
    | '/_authenticated/appointments'
    | '/_authenticated/audit-logs'
    | '/_authenticated/billing'
    | '/_authenticated/chatbot'
    | '/_authenticated/dashboard'
    | '/_authenticated/doctors'
    | '/_authenticated/emr'
    | '/_authenticated/notifications'
    | '/_authenticated/ocr'
    | '/_authenticated/patients'
    | '/_authenticated/search'
    | '/auth/callback'
    | '/portal/_portal'
    | '/_authenticated/ai/clinical-search'
    | '/_authenticated/ai/notes'
    | '/_authenticated/ai/summary'
    | '/portal/_portal/appointments'
    | '/portal/_portal/bills'
    | '/portal/_portal/chatbot'
    | '/portal/_portal/create-profile'
    | '/portal/_portal/notifications'
    | '/portal/_portal/overview'
    | '/portal/_portal/records'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  PortalPortalRoute: typeof PortalPortalRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/_portal': {
      id: '/portal/_portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/search': {
      id: '/_authenticated/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AuthenticatedSearchRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/patients': {
      id: '/_authenticated/patients'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof AuthenticatedPatientsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ocr': {
      id: '/_authenticated/ocr'
      path: '/ocr'
      fullPath: '/ocr'
      preLoaderRoute: typeof AuthenticatedOcrRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/emr': {
      id: '/_authenticated/emr'
      path: '/emr'
      fullPath: '/emr'
      preLoaderRoute: typeof AuthenticatedEmrRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/doctors': {
      id: '/_authenticated/doctors'
      path: '/doctors'
      fullPath: '/doctors'
      preLoaderRoute: typeof AuthenticatedDoctorsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/chatbot': {
      id: '/_authenticated/chatbot'
      path: '/chatbot'
      fullPath: '/chatbot'
      preLoaderRoute: typeof AuthenticatedChatbotRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/billing': {
      id: '/_authenticated/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthenticatedBillingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/audit-logs': {
      id: '/_authenticated/audit-logs'
      path: '/audit-logs'
      fullPath: '/audit-logs'
      preLoaderRoute: typeof AuthenticatedAuditLogsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/appointments': {
      id: '/_authenticated/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AuthenticatedAppointmentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/portal/_portal/records': {
      id: '/portal/_portal/records'
      path: '/records'
      fullPath: '/portal/records'
      preLoaderRoute: typeof PortalPortalRecordsRouteImport
      parentRoute: typeof PortalPortalRoute
    }
    '/portal/_portal/overview': {
      id: '/portal/_portal/overview'
      path: '/overview'
      fullPath: '/portal/overview'
      preLoaderRoute: typeof PortalPortalOverviewRouteImport
      parentRoute: typeof PortalPortalRoute
    }
    '/portal/_portal/notifications': {
      id: '/portal/_portal/notifications'
      path: '/notifications'
      fullPath: '/portal/notifications'
      preLoaderRoute: typeof PortalPortalNotificationsRouteImport
      parentRoute: typeof PortalPortalRoute
    }
    '/portal/_portal/create-profile': {
      id: '/portal/_portal/create-profile'
      path: '/create-profile'
      fullPath: '/portal/create-profile'
      preLoaderRoute: typeof PortalPortalCreateProfileRouteImport
      parentRoute: typeof PortalPortalRoute
    }
    '/portal/_portal/chatbot': {
      id: '/portal/_portal/chatbot'
      path: '/chatbot'
      fullPath: '/portal/chatbot'
      preLoaderRoute: typeof PortalPortalChatbotRouteImport
      parentRoute: typeof PortalPortalRoute
    }
    '/portal/_portal/bills': {
      id: '/portal/_portal/bills'
      path: '/bills'
      fullPath: '/portal/bills'
      preLoaderRoute: typeof PortalPortalBillsRouteImport
      parentRoute: typeof PortalPortalRoute
    }
    '/portal/_portal/appointments': {
      id: '/portal/_portal/appointments'
      path: '/appointments'
      fullPath: '/portal/appointments'
      preLoaderRoute: typeof PortalPortalAppointmentsRouteImport
      parentRoute: typeof PortalPortalRoute
    }
    '/_authenticated/ai/summary': {
      id: '/_authenticated/ai/summary'
      path: '/ai/summary'
      fullPath: '/ai/summary'
      preLoaderRoute: typeof AuthenticatedAiSummaryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ai/notes': {
      id: '/_authenticated/ai/notes'
      path: '/ai/notes'
      fullPath: '/ai/notes'
      preLoaderRoute: typeof AuthenticatedAiNotesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ai/clinical-search': {
      id: '/_authenticated/ai/clinical-search'
      path: '/ai/clinical-search'
      fullPath: '/ai/clinical-search'
      preLoaderRoute: typeof AuthenticatedAiClinicalSearchRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedAppointmentsRoute: typeof AuthenticatedAppointmentsRoute
  AuthenticatedAuditLogsRoute: typeof AuthenticatedAuditLogsRoute
  AuthenticatedBillingRoute: typeof AuthenticatedBillingRoute
  AuthenticatedChatbotRoute: typeof AuthenticatedChatbotRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDoctorsRoute: typeof AuthenticatedDoctorsRoute
  AuthenticatedEmrRoute: typeof AuthenticatedEmrRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedOcrRoute: typeof AuthenticatedOcrRoute
  AuthenticatedPatientsRoute: typeof AuthenticatedPatientsRoute
  AuthenticatedSearchRoute: typeof AuthenticatedSearchRoute
  AuthenticatedAiClinicalSearchRoute: typeof AuthenticatedAiClinicalSearchRoute
  AuthenticatedAiNotesRoute: typeof AuthenticatedAiNotesRoute
  AuthenticatedAiSummaryRoute: typeof AuthenticatedAiSummaryRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedAppointmentsRoute: AuthenticatedAppointmentsRoute,
  AuthenticatedAuditLogsRoute: AuthenticatedAuditLogsRoute,
  AuthenticatedBillingRoute: AuthenticatedBillingRoute,
  AuthenticatedChatbotRoute: AuthenticatedChatbotRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDoctorsRoute: AuthenticatedDoctorsRoute,
  AuthenticatedEmrRoute: AuthenticatedEmrRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedOcrRoute: AuthenticatedOcrRoute,
  AuthenticatedPatientsRoute: AuthenticatedPatientsRoute,
  AuthenticatedSearchRoute: AuthenticatedSearchRoute,
  AuthenticatedAiClinicalSearchRoute: AuthenticatedAiClinicalSearchRoute,
  AuthenticatedAiNotesRoute: AuthenticatedAiNotesRoute,
  AuthenticatedAiSummaryRoute: AuthenticatedAiSummaryRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface PortalPortalRouteChildren {
  PortalPortalAppointmentsRoute: typeof PortalPortalAppointmentsRoute
  PortalPortalBillsRoute: typeof PortalPortalBillsRoute
  PortalPortalChatbotRoute: typeof PortalPortalChatbotRoute
  PortalPortalCreateProfileRoute: typeof PortalPortalCreateProfileRoute
  PortalPortalNotificationsRoute: typeof PortalPortalNotificationsRoute
  PortalPortalOverviewRoute: typeof PortalPortalOverviewRoute
  PortalPortalRecordsRoute: typeof PortalPortalRecordsRoute
}

const PortalPortalRouteChildren: PortalPortalRouteChildren = {
  PortalPortalAppointmentsRoute: PortalPortalAppointmentsRoute,
  PortalPortalBillsRoute: PortalPortalBillsRoute,
  PortalPortalChatbotRoute: PortalPortalChatbotRoute,
  PortalPortalCreateProfileRoute: PortalPortalCreateProfileRoute,
  PortalPortalNotificationsRoute: PortalPortalNotificationsRoute,
  PortalPortalOverviewRoute: PortalPortalOverviewRoute,
  PortalPortalRecordsRoute: PortalPortalRecordsRoute,
}

const PortalPortalRouteWithChildren = PortalPortalRoute._addFileChildren(
  PortalPortalRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  PortalPortalRoute: PortalPortalRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
